Simplify build
justeat/kongverge pull request #1
Opened 2018-09-28 19:50 UTC by slang25

Defer docker for when you run `dotnet test`, so that `dotnet build` is simple and has less dependencies.

2018-09-30 22:02 UTC, JosephWoodward commented on .gitignore
> +.idea
I approve 👍

2018-10-01 10:25 UTC, shaynevanasperen requested changes

2018-10-01 10:25 UTC, shaynevanasperen commented on test/Kongverge.IntegrationTests/Kongverge.IntegrationTests.csproj
> +  <Target Name="BuildDockerServices" BeforeTargets="VSTest">
Unfortunately this change breaks the developer experience of being able to run tests with `ReSharper` or `NCrunch`. In fact, I can't even get it to work properly the first time when running `dotnet test` (it fails, and then when trying again it succeeeds).

I think it's best to keep this as `AfterTargets="Build"` as it is technically a build step (which does a no-op if you've already got the images/containers cached). We could potentially add a condition so that it doesn't event try to run if you don't have Docker installed, however I'm more inclined to just state in the `README` or `CONTRIBUTING` docs that having Docker installed is a prerequisite for development of this code.

2018-10-01 10:25 UTC, shaynevanasperen commented on .appveyor.yml
> +    docker-compose -f test/Kongverge.IntegrationTests/docker-compose.yml up --no-start
This should not have the `--no-start` option. And if we're going to keep the build step (`docker-compose up`) happening at build time, then this should be `docker-compose start`.

2018-10-01 10:25 UTC, shaynevanasperen commented on .appveyor.yml
> +    dotnet test test/Kongverge.Tests/Kongverge.Tests.csproj
This should have the `--no-build` option.

2018-10-01 10:25 UTC, shaynevanasperen commented on .appveyor.yml
> +    dotnet test test/Kongverge.IntegrationTests/Kongverge.IntegrationTests.csproj
This should have the `--no-build` option.

2018-10-01 10:25 UTC, shaynevanasperen commented on .appveyor.yml
> +    docker-compose -f test/Kongverge.IntegrationTests/docker-compose.yml down
I think this only needs to be `docker-compose stop`. Since the entire environment will be torn down anyway by AppVeyor, there's not much point doing a full teardown of the docker images/containers etc.

2018-10-01 10:38 UTC, slang25 commented on test/Kongverge.IntegrationTests/Kongverge.IntegrationTests.csproj
> +  <Target Name="BuildDockerServices" BeforeTargets="VSTest">
I need to make some tweaks, but it should still work with NCrunch etc, if it doesn't then we can detect it (there is an env var `NCRUNCH` we can detect as a property in MSBuild) and workaround it.

If this is how it's desired to work then great, but I found it odd that I cannot clone and build without first starting docker. I thought a nicer approach would be to only attempt to start up the containers as a pre-req step for running tests.

2018-12-19 14:15 UTC, closed without merging